import { useParams, Link } from "react-router-dom";
import { usePitchData } from "@/hooks/usePitchData";
import { KeyMetricsHeader } from "@/components/KeyMetricsHeader";
import { ThesisStatement } from "@/components/ThesisStatement";
import { DistributionChart } from "@/components/DistributionChart";
import { CDFChart } from "@/components/CDFChart";
import { DriverConcentrationCard } from "@/components/DriverConcentrationCard";
import { CalibrationPanel } from "@/components/CalibrationPanel";
import { TornadoChart } from "@/components/TornadoChart";
import { VarianceContributionChart } from "@/components/VarianceContributionChart";
import { InputDistributionsPanel } from "@/components/InputDistributionsPanel";
import { ScenarioPanel } from "@/components/ScenarioPanel";
import { fmtAbsDate, fmtPrice, modelTypeLabel } from "@/lib/format";

export function PitchDetailPage() {
  const { id } = useParams();
  const { data, loading, error } = usePitchData(id);

  if (loading) {
    return (
      <div className="container">
        <span className="spinner" /> Loading {id}…
      </div>
    );
  }
  if (error || !data) {
    return (
      <div className="container empty-state">
        <p>Could not load pitch: {error}</p>
        <Link to="/">← Back to all pitches</Link>
      </div>
    );
  }

  const copyPermalink = () => {
    const url = `${window.location.origin}/pitch/${data.pitch_id}`;
    navigator.clipboard?.writeText(url);
  };

  return (
    <div className="container">
      <div style={{ marginBottom: 14, fontSize: 13, color: "var(--text-muted)" }}>
        <Link to="/">Pitches</Link> → {data.ticker}
      </div>

      <div className="detail-header">
        <div>
          <h1 className="ticker">
            {data.ticker}
            {data.is_draft && (
              <span className="draft-badge" style={{ marginLeft: 14, fontSize: 12 }}>
                draft
              </span>
            )}
          </h1>
          <div className="meta">
            {modelTypeLabel(data.model_type)} • Current price {fmtPrice(data.current_price)} •{" "}
            {data.n_simulations.toLocaleString()} simulations • generated{" "}
            {fmtAbsDate(data.generated_at)}
          </div>
        </div>
        <button className="chip" onClick={copyPermalink}>
          Copy permalink
        </button>
      </div>

      <KeyMetricsHeader data={data} />

      <ThesisStatement data={data} />

      <div className="section two-col">
        <DistributionChart
          distribution={data.distribution}
          currentPrice={data.current_price}
          expectedReturn={data.probability_analysis.expected_return}
          probabilityUpside={data.probability_analysis.probability_upside}
        />
        <CDFChart distribution={data.distribution} currentPrice={data.current_price} />
      </div>

      <DriverConcentrationCard concentration={data.concentration} />

      {data.calibration && data.calibration.length > 0 && (
        <CalibrationPanel entries={data.calibration} />
      )}

      {data.tornado && data.tornado.length > 0 && (
        <div className="section two-col">
          <TornadoChart entries={data.tornado} centerValue={data.distribution.median} />
          <VarianceContributionChart entries={data.tornado} />
        </div>
      )}

      <InputDistributionsPanel inputs={data.inputs} />

      {data.catalysts && data.catalysts.length > 0 && (
        <ScenarioPanel
          catalysts={data.catalysts}
          scenarios={data.scenarios}
          meanFairValue={data.distribution.mean}
        />
      )}

      <div className="footer">
        Generated by IMA Monte Carlo •{" "}
        <Link to="/about">methodology</Link> • seed: {data.random_seed ?? "—"}
      </div>
    </div>
  );
}
